#---(in meters)---
footprint: [[0.15, 0.20], [0.15, -0.20], [-0.15, -0.20], [-0.15, 0.20],]

#transform_tolerance: 0.2
#map_type: costmap

#obstacle_layer:
# enabled: true
# obstacle_range: 2.0
# raytrace_range: 2.5
# inflation_radius: 0.3
# track_unknown_space: false
# combination_method: 1

# observation_sources: laser_scan_sensor
# laser_scan_sensor: {data_type: LaserScan, topic: Jacto_01/Lidar2D/LidarScan, marking: true, clearing: true}


#inflation_layer:
#  enabled:              true
#  cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
#  inflation_radius:     0.0  # max. distance from an obstacle at which costs are incurred for planning paths.
#---(in meters)---

transform_tolerance: 0.3
map_type: costmap

obstacle_layer:
 enabled: true
# obstacle_range: 2.0
# raytrace_range: 2.5
 inflation_radius: 0.08
 track_unknown_space: true
 combination_method: 1

 observation_sources: laser_scan_sensor point_cloud_sensor
 laser_scan_sensor: {data_type: LaserScan, topic: Zordon/Lidar2D/LidarScan, marking: true, clearing: true}

 point_cloud_sensor: {sensor_frame: camera_depth_optical_frame, data_type: PointCloud2, topic: /rtabmap/cloud_obstacles, marking: true, clearing: true, max_obstacle_height: 2.5, min_obstacle_height: 0.28, observation_persistence: 0.0, expected_update_rate: 5}

static_layer:
  enabled:              true
  map_topic:              "map"
inflation_layer:
  enabled:              true
  cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.05  # max. distance from an obstacle at which costs are incurred for
