NavfnROS:
  visualize_potential: false    
  allow_unknown: false          
                                
  planner_window_x: 5.0         
  planner_window_y: 5.0         

  default_tolerance: 0.3
