frequency: 10

odom0_config: [false, false, false,
               false, false, true,
               true, false, false,
               false, false, false,
               false, false, false]
odom0_differential: false

odom1_config: [true, true, true,
                false, false, true,
                true,  true, false,
                false, false, true,
                false, false, false]
odom1_differential: false

imu0_config: [false, false, false,
                false, false, true,
                true, true, false,
                false, false, true,
                false, false, false]
imu0_differential: false


