local_costmap:
  global_frame: /Mirela_odom
  robot_base_frame: /Mirela_base
  update_frequency: 10.0
  publish_frequency: 10.0
  static_map: false
  rolling_window: true
  width: 2.0
  height: 2.0
  resolution: 0.1

  plugins:
   - {name: static_layer,        type: "costmap_2d::StaticLayer"}
   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}

